# Generated by Django 5.0.4 on 2024-04-10 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='info',
            field=models.CharField(default=False, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 11, 0, 16, 32, 770945)),
        ),
    ]
